<?xml version="1.0"?>
<!DOCTYPE reference_node_types [
<!ELEMENT reference_node_types (reference_node_type)*>
<!ELEMENT reference_node_type (#PCDATA | match_group)*>
<!ATTLIST reference_node_type
name CDATA #REQUIRED
icon CDATA #REQUIRED
icon_small CDATA #REQUIRED
>
<!ELEMENT match_group (#PCDATA | match)*>
<!ATTLIST match_group
appended_operator (and|or|none) "or" 
>
<!ELEMENT match (#PCDATA)>
<!ATTLIST match
term CDATA #REQUIRED
type (starts_with|ends_with|contains|length_equals|length_less|length_more|isDirectory) "ends_with" 
>
]>
<reference_node_types>
	<reference_node_type name="LabSpace" icon="labspace.png" icon_small="labspace_sm.png">
		<match_group appended_operator="and">	
			<match term="labspace.open.ac.uk" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="LearnSpace" icon="learnspace.png" icon_small="learnspace_sm.png">
		<match_group appended_operator="and">	
			<match term="openlearn.open.ac.uk" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Open2" icon="open2.png" icon_small="open2_sm.png">
		<match_group appended_operator="and">	
			<match term="open2.net" type="contains" />
		</match_group>
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
		</match_group>
	</reference_node_type>		
	<reference_node_type name="General Web Pages" icon="html.gif" icon_small="html_sm.gif">
		<match_group appended_operator="or">
			<match term="www" type="starts_with" />	
			<match term="http:" type="starts_with" />
			<match term="https:" type="starts_with" />
			<match term=".html" type="ends_with" />
			<match term=".htm" type="ends_with" />
			<match term=".url" type="ends_with" />	
			<match term=".asp" type="ends_with" />
			<match term=".php" type="ends_with" />
			<match term=".jsp" type="ends_with" />
		</match_group>
	</reference_node_type>		
	<reference_node_type name="Internal Reference" icon="reference-internal.png" icon_small="reference-internal_sm.png">
		<match_group appended_operator="none">
			<match term="comp://" type="starts_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Word File" icon="word.gif" icon_small="word_sm.gif">
		<match_group appended_operator="or">
			<match term=".doc" type="ends_with" />
			<match term=".docx" type="ends_with" />
			<match term=".docm" type="ends_with" />
			<match term=".odt" type="ends_with" />			
		</match_group>
	</reference_node_type>	
	<reference_node_type name="Access File" icon="access.gif" icon_small="access_sm.gif">
		<match_group appended_operator="or">
			<match term=".mdb" type="ends_with" />
			<match term=".accdb" type="ends_with" />
			<match term=".odb" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="Excel File" icon="excel.gif" icon_small="excel_sm.gif">
		<match_group appended_operator="or">
			<match term=".xls" type="ends_with" />
			<match term=".xlsx" type="ends_with" />
			<match term=".xlsm" type="ends_with" />
			<match term=".ods" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="PowerPoint File" icon="powerpoint.gif" icon_small="powerpoint_sm.gif">
		<match_group appended_operator="or">
			<match term=".ppt" type="ends_with" />
			<match term=".pptx" type="ends_with" />
			<match term=".pptm" type="ends_with" />
			<match term=".pps" type="ends_with" />
			<match term=".ppsx" type="ends_with" />
			<match term=".ppsm" type="ends_with" />
			<match term=".odp" type="ends_with" />			
		</match_group>
	</reference_node_type>
	<reference_node_type name="RSS" icon="feed-icon.png" icon_small="feed-icon_sm.png">
		<match_group appended_operator="or">
			<match term="feed://" type="starts_with" />
		</match_group>
		<match_group appended_operator="none">
			<match term="rss.xml" type="ends_with" />
		</match_group>		
	</reference_node_type>					
	<reference_node_type name="XML File" icon="xml.gif" icon_small="xml_sm.gif">
		<match_group appended_operator="none">
			<match term=".xml" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="XSL File" icon="xsl.gif" icon_small="xsl_sm.gif">
		<match_group appended_operator="none">
			<match term=".xsl" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Text File" icon="text.gif" icon_small="text_sm.gif">
		<match_group appended_operator="none">
			<match term=".txt" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="PDF File" icon="acrobat.gif" icon_small="acrobat_sm.gif">
		<match_group appended_operator="none">
			<match term=".pdf" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Java File" icon="java.gif" icon_small="java_sm.gif">
		<match_group appended_operator="none">
			<match term=".java" type="ends_with" />
		</match_group>
	</reference_node_type>
	<reference_node_type name="Movie Files" icon="mediaplayer.gif" icon_small="mediaplayer_sm.gif">
		<match_group appended_operator="or">
			<match term=".avi" type="ends_with" />	
			<match term=".mov" type="ends_with" />
			<match term=".wmv" type="ends_with" />
			<match term=".ram" type="ends_with" />
		</match_group>
	</reference_node_type>			
	<reference_node_type name="Email" icon="email.gif" icon_small="email_sm.gif">
		<match_group appended_operator="and">
			<match term="@" type="contains" />
		</match_group>
		<match_group appended_operator="none">
			<match term="100" type="length_less" />
		</match_group>		
	</reference_node_type>
	<reference_node_type name="Folder" icon="folder.png" icon_small="folder_sm.png">
		<match_group appended_operator="or">
			<match term="\\" type="starts_with" />
		</match_group>
		<match_group appended_operator="none">
			<match term="" type="isDirectory" />
		</match_group>		
	</reference_node_type>		
</reference_node_types>